import { abrirNavegador, celular, capturas, reportar, esperar } from './comun.mjs'
const browser = await abrirNavegador()
const errores = []
const shot = capturas()

// Bodega de ejemplo con movimiento desde la bienvenida
const page = await celular(browser, 'A', errores, { conEjemplo: false })
await page.getByPlaceholder(/Doña Carmen/).fill('Bodega Doña Carmen')
await page.getByRole('button', { name: /bodega de ejemplo con movimiento/ }).click()
await page.getByText('Inca Kola 500ml').waitFor({ timeout: 20000 })
await shot(page, '50-vender-iconos')
esperar((await page.locator('.tarjeta-producto .icono-producto.emoji').count()) >= 20, 'los productos muestran ícono automático')
esperar((await page.locator('.chip', { hasText: 'Más vendidos' }).count()) === 1, 'hay historial: aparece "Más vendidos"')

await page.getByRole('button', { name: 'Caja' }).click()
await page.locator('.fila-simple.clic').first().waitFor()
const hoy = (await page.locator('.hero-cifra').innerText()).replace(/\n/g, ' ')
esperar(/\d+ ventas/.test(hoy), `caja de hoy con ventas: ${hoy}`)
const semana = await page.locator('.subtitulo', { hasText: 'Últimos 7 días' }).innerText()
esperar(!semana.includes('S/ 0.00 vendido'), `semana con ventas: ${semana}`)
await shot(page, '51-caja-demo')
await page.getByRole('button', { name: 'Fiados' }).click()
await page.locator('.item').first().waitFor()
esperar((await page.locator('.item').count()) === 4, 'cuatro clientes de ejemplo')
await shot(page, '52-fiados-demo')

// Deshacer última venta
await page.getByRole('button', { name: 'Vender' }).click()
const antes = await page.getByRole('button', { name: /Inca Kola 500ml/ }).locator('.tp-stock').innerText()
await page.getByRole('button', { name: /Inca Kola 500ml/ }).click()
await page.getByRole('button', { name: /^Cobrar/ }).click()
await page.getByRole('button', { name: /^Confirmar/ }).click()
await page.getByText(/Venta registrada/).waitFor()
await shot(page, '53-deshacer')
await page.getByRole('button', { name: 'Deshacer' }).click()
await page.getByText(/Venta deshecha/).waitFor()
const despues = await page.getByRole('button', { name: /Inca Kola 500ml/ }).locator('.tp-stock').innerText()
esperar(antes === despues, `deshacer devuelve el stock (${antes} → ${despues})`)

// Guía
await page.getByRole('button', { name: '¿Cómo se usa?' }).click()
await page.getByText('¿Cómo vendo?').waitFor()
await shot(page, '54-guia')
await page.getByRole('button', { name: 'Entendido' }).click()

// Foto e ícono de producto
await page.getByRole('button', { name: 'Stock' }).click()
await page.locator('.item-cuerpo', { hasText: 'Sublime' }).click()
await page.getByRole('button', { name: /Elegir ícono/ }).click()
await page.locator('.emoji-opcion', { hasText: '🎁' }).click()
await page.getByRole('button', { name: 'Guardar' }).click()
await page.getByText('Producto actualizado').waitFor()
esperar((await page.locator('.item', { hasText: 'Sublime' }).locator('.icono-producto').innerText()) === '🎁', 'ícono elegido a mano se guarda')
await page.locator('.item-cuerpo', { hasText: 'Sublime' }).click()
// Foto: subimos una imagen generada (PNG 2x2) por el input de archivo
await page.locator('input[type=file][accept="image/*"]').setInputFiles({ name: 'foto.png', mimeType: 'image/png', buffer: Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAIAAAACCAYAAABytg0kAAAAEklEQVR4nGP4z8DwHwyBDCAAABn8BPl6hGmVAAAAAElFTkSuQmCC', 'base64') })
await page.locator('.imagen-producto img').waitFor()
await shot(page, '55-foto')
await page.getByRole('button', { name: 'Guardar' }).click()
await page.locator('.modal').waitFor({ state: 'hidden' })
await page.locator('.item', { hasText: 'Sublime' }).locator('img.icono-producto').waitFor({ timeout: 5000 })
esperar((await page.locator('.item', { hasText: 'Sublime' }).locator('img.icono-producto').count()) === 1, 'la foto se guarda y se muestra')

// Letra grande
await page.getByRole('button', { name: 'Más' }).click()
await page.getByRole('button', { name: /Letra grande/ }).click()
await page.waitForTimeout(200)
esperar((await page.evaluate(() => document.documentElement.dataset.letra)) === 'grande', 'letra grande activa')
await shot(page, '56-letra-grande')

// Modo ayudante con PIN
await page.getByRole('button', { name: /Crear PIN y activar/ }).click()
await page.getByLabel('PIN', { exact: true }).fill('1234')
await page.getByLabel('Repite el PIN').fill('1234')
await page.getByRole('button', { name: /Guardar y entrar/ }).click()
await page.getByText(/Modo ayudante activado/).waitFor()
await page.getByRole('button', { name: 'Caja' }).click()
await page.locator('.hero-cifra').waitFor()
esperar(!(await page.locator('.hero-cifra').innerText()).includes('Ganancia'), 'modo ayudante oculta la ganancia')
esperar((await page.locator('.banner-accion').count()) === 0, 'modo ayudante oculta el resumen del mes')
await page.getByRole('button', { name: 'Stock' }).click()
esperar((await page.getByRole('button', { name: '+ Producto' }).count()) === 0, 'modo ayudante no puede crear productos')
await page.getByRole('button', { name: 'Más' }).click()
await shot(page, '57-modo-ayudante')
await page.getByRole('button', { name: /Volver a modo dueña/ }).click()
await page.getByLabel('PIN', { exact: true }).fill('0000')
await page.getByRole('button', { name: 'Entrar' }).click()
await page.getByText('PIN incorrecto').waitFor()
await page.getByLabel('PIN', { exact: true }).fill('1234')
await page.getByRole('button', { name: 'Entrar' }).click()
await page.getByText('Modo dueña', { exact: true }).waitFor()
await page.getByRole('button', { name: 'Caja' }).click()
await page.locator('.hero-cifra').waitFor()
esperar((await page.locator('.hero-cifra').innerText()).includes('Ganancia'), 'de vuelta en modo dueña se ve la ganancia')

reportar(errores)
await browser.close()
